export const FRICTION = 1
export const RADIUS = 20
export const MINMOVE = 0.1
export const ACCELERATION_CHUTE = 1
export const ACCELARATION_HORIZ = 0.08
export const BALLLIFE = 4
export const PLAYERLIFE = 10
export const DELAY_ACCELERATION: number = 1
export const DECELERATION: number = 0.2
export const VITESSE_MAX: number = 7