export const FRICTION = 1
export const RADIUS = 25
export const MINMOVE = 0.1
export const ACCELERATION_CHUTE = 0.5
export const ACCELARATION_HORIZ = 0.08
export const VITESSE_INIT_SAUT = -0.75
export const BALLLIFE = 4
export const PLAYERLIFE = 10
export const DELAY_ACCELERATION: number = 1
export const DECELERATION: number = 0.2
export const VITESSE_MAX: number = 7
export const DEBUG_ON: boolean = true
export const MAX_X: number = 1200;
export const TAILLE_ENEMIE = 80
export const ENEMIE_VITESSE = 2
const MAX_Y: number = 800;